### ISSUE TITLE
support currency symbols

### ISSUE THREAD

**Issue by bukinoshita** [hugomd/is-currency#1]
I think that would be cool to support currency symbols as well. What do you think?

`$`, `R$`, `€`, `£`, etc...

**Comment by hugomd** [comment]
@bukinoshita Currency symbols aren't currently included in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) but I do agree, it would be useful to be able to convert and validate currency symbols. 

I think this is out of scope for this particular package, but I've made [`is-currency-symbol`](https://github.com/hugomd/is-currency-symbol) and will add the functionality there, and list it on this repository as related.

Thanks for raising this issue!

✌️

**Comment by bukinoshita** [comment]
Awesome!
